//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2._0.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public int ID_Employee { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int Gender { get; set; }
        public int Age { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public int PostID { get; set; }
        public System.DateTime WorkingStartDate { get; set; }
        public int PassportSerial { get; set; }
        public int PassportNumber { get; set; }
        public long INN { get; set; }
        public long SNILS { get; set; }
        public int HotelID { get; set; }
    
        public virtual EmployersPost EmployersPost { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
