//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2._0.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kastil
    {
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int Number { get; set; }
        public int ID_TipeRoom { get; set; }
        public int ID_Room { get; set; }
        public int ID_Hotel { get; set; }
    }
}
